---
title: "Reproducible Research: Peer Assessment 1"
output:
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
activity <- read.csv("activity.csv")
activity$date <- as.Date(activity$date)
str(activity)
summary(activity)
head(activity)
```

## What is mean total number of steps taken per day?
```{r, echo=TRUE}

steps_per_day <- aggregate(steps ~ date, data = activity, sum, na.rm = TRUE)
hist(steps_per_day$steps,
     breaks = 20,
     col = "lightblue",
     main = "Histogram of Total Steps per Day",
     xlab = "Total Steps per Day")
mean(steps_per_day$steps)
median(steps_per_day$steps)
```
## What is the average daily activity pattern?
```{r}
interval_avg <- aggregate(steps ~ interval, data = activity, mean, na.rm = TRUE)

plot(interval_avg$interval,
interval_avg$steps,
type = "l",
col = "red",
xlab = "5-minute Interval",
ylab = "Average Steps",
main = "Average Daily Activity Pattern")
interval_avg[which.max(interval_avg$steps),]
```

## Imputing missing values

```{r}
sum(is.na(activity$steps))
activity_imputed <- activity

interval_means <- tapply(activity$steps,
                          activity$interval,
                          mean,
                          na.rm = TRUE)

na_idx <- is.na(activity_imputed$steps)
activity_imputed$steps[na_idx] <-
interval_means[as.character(activity_imputed$interval[na_idx])]
steps_per_day_imputed <- aggregate(steps ~ date, data = activity_imputed, sum)

hist(steps_per_day_imputed$steps,
breaks = 20,
col = "lightgreen",
main = "Histogram of Total Steps per Day (Imputed)",
xlab = "Total Steps per Day")

steps_per_day_imputed <- aggregate(steps ~ date,
data = activity_imputed, sum)
mean(steps_per_day_imputed$steps)
median(steps_per_day_imputed$steps)
```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
activity_imputed$daytype <- ifelse(
weekdays(activity_imputed$date) %in% c("Saturday", "Sunday"),
"weekend",
"weekday"
)

activity_imputed$daytype <- factor(activity_imputed$daytype)

interval_daytype <- aggregate(
steps ~ interval + daytype,
data = activity_imputed,
mean
)
```
# Panel plot
```{r panel-plot, echo=TRUE, fig.height=8, fig.width=7}
par(mfrow = c(2, 1))

for (type in levels(interval_daytype$daytype)) {
subset_data <- interval_daytype[interval_daytype$daytype == type, ]
plot(subset_data$interval,
subset_data$steps,
type = "l",
main = paste("Average Steps -", type),
xlab = "5-minute Interval",
ylab = "Average Steps")
}
```
